### ISSUE TITLE
Laravel cashier breaking project

### ISSUE THREAD

**Issue by gautam-patadiya** [miracuthbert/saas-boilerplate#2]
In Cashier.php line 73:

Unable to guess symbol for currency. Please explicitly specify it. 

I tried this solution but not working.
https://stackoverflow.com/questions/27945163/how-to-set-the-default-currency-of-laravel-cashier#answer-37139387

**Comment by miracuthbert** [comment]
Please make sure you have laravel/cashier installed.

If you are not using Cashier, you may remove its functionality in _StripeServiceProvider_; which may be the reason your project is breaking.

Checkout this link on how to configure currency when using cashier: [Laravel cashier](https://laravel.com/docs/5.6/billing)

Sorry, for the late response. I hope the suggestions above may help.

**Comment by erigglem** [comment]
@gautam-patadiya - is this a new install? you probably didn't create a .env file. It looks there for the currency and currency symbol, sounds like its not able to access that from your .env file. If you do have a .env file, double-check the permissions on it.

**Comment by gautam-patadiya** [comment]
@erigglem Yes, it's fresh installation

**Comment by gautam-patadiya** [comment]
@miracuthbert I'm little much familiar with Laravel. I already installed Cashier.

**Comment by cnngraphics** [comment]
error on php artisan migrate (fresh install) conflict with \vendor\laravel\cashier\migrations\create...

**Comment by miracuthbert** [comment]
Migrations for cashier have been published already, so you can disable them by calling `Cashier::ignoreMigrations()` in `boot` method of `AppServiceProvider`. 

**Note**: Ensure that the published migrations match the cashier version, if you prefer the above option.

**Recommended**: Delete the **published** cashier migrations and let the package handle the loading of the migrations.
