### ISSUE TITLE
Missing Super Admin?

### ISSUE THREAD

**Issue by erigglem** [miracuthbert/saas-boilerplate#3]
Am I missing something? There is no "super admin" for logging in and seeing all users, companies, etc. For actually managing the SaaS app... No way to create/edit subscription plans/pricing except for to modify the database or build out a super admin backend? I hope that makes sense.

**Comment by miracuthbert** [comment]
To create a **super / root admin**
Run `php artisan admin:assign-role youremail@example.org admin-root`. Substitute `youremail@example.org` with an _existing user email_. _**admin-root**_ is the **default root Admin role**.

For more details check the **readme** file under _installation_ and _commands_ section.

**Comment by miracuthbert** [comment]
I'll consider this issue resolved.
