### ISSUE TITLE
Error php artisan migrate

### ISSUE THREAD

**Issue by kristiantenfen** [miracuthbert/saas-boilerplate#4]
Fatal error: Uncaught ReflectionException: Class SAASBoilerplate\App\Console\Kernel does not exist in /Applications/MAMP/htdocs/saas-boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php:767
Stack trace:
#0 /Applications/MAMP/htdocs/saas-boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('SAASBoilerplate...')
#1 /Applications/MAMP/htdocs/saas-boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('SAASBoilerplate...')
#2 /Applications/MAMP/htdocs/saas-boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('SAASBoilerplate...', Array)
#3 /Applications/MAMP/htdocs/saas-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(740): Illuminate\Container\Container->make('SAASBoilerplate...', Array)
#4 /Applications/MAMP/htdocs/saas-boilerplate/vendor/laravel/framework/src/Illuminate/Container/Co in /Applications/MAMP/htdocs/saas-boilerplate/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767
MacBook-Pro-de-Kristian:saas-boilerplate kristiantenfen$ php artisan migrate

**Comment by Tjoosten** [comment]
found any fix?

**Comment by kristiantenfen** [comment]
> found any fix?

No

**Comment by kylngr** [comment]
I started laravel 5 mins ago so my answer may not have any impact on your situation. 
I got the same error while installing. If I do not change the namespace of the app with "php artisan app:name" it just works.

**Comment by LunarDevelopment** [comment]
I sorted a similar issue in my own project earlier - it was caused because the `php artisan app:name` didn't rename the namespace within the seeding folder. (but did so everywhere else in the app) 

So when the seeder classes look for the models under SAASBoilerplate\... they're not found.

**Comment by miracuthbert** [comment]
I have fixed this issue by overriding the default `php artisan app:name` command to search and replace the old namespace with a new one in the entire project. See this [commit](https://github.com/miracuthbert/saas-boilerplate/commit/69b7f4faa8095009eb1b4f783ac09bb6854e4541).

Sorry for the late response, hope it helps.
