### ISSUE TITLE
ReflectionException  : Class RoleTableSeeder does not exist

### ISSUE THREAD

**Issue by devoided** [miracuthbert/saas-boilerplate#6]
Trying to install and can only get to step 6...

**php artisan db:seed --class=RoleTableSeeder**

I get the following error:

**ReflectionException  : Class RoleTableSeeder does not exist**

I've tried researching (**composer dumpautoload** and other fixes but none work)

**Comment by miracuthbert** [comment]
@devoided, hope you found a solution. If not, kindly open an issue with at least a snapshot of the error.

**Comment by mutuku** [comment]
I am getting a similar error when I run 

`php artisan db:seed --class=RoleTableSeeder`

Please see error below

`Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'SAASBoilerplate\Domain\Users\Models\Role' not found

  at /var/www/html/saas/database/seeds/RoleTableSeeder.php:28
    24|             ]
    25|         ];
    26| 
    27|         foreach ($roles as $role) {
  > 28|             Role::create($role);
    29|         }
    30| 
    31|         $permissions = [
    32|             [

  Exception trace:

  1   RoleTableSeeder::run()
      /var/www/html/saas/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  2   call_user_func_array([])
      /var/www/html/saas/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.
`

**Comment by miracuthbert** [comment]
Try replacing `SAASBoilerplate` part of the namespace `SAASBoilerplate\Domain\Users\Models\Role` with the new app namespace you setup in `Step 4`.
